Repository lolcatbois/ignore-it, pull requests merged in 2020-11, with the labels that each got.

#35 ADD adding flag (with this its also chainable)
  lib/ignore_it.rb
  lib/ignore_it/creator.rb
Labels: enhancement

#41 Feature/own gitignore files
  lib/ignore_it.rb
  lib/ignore_it/creator.rb
  lib/ignore_it/list.rb
Labels: enhancement, refactoring

#46 Add Thor as default parser
  bin/ignore-it
  ignore_it.gemspec
  lib/ignore_it.rb
  lib/ignore_it/creator.rb
  rubocop.yml
Labels: feature

#48 ADD output parameter functionality
  lib/ignore_it.rb
  lib/ignore_it/config.rb
  lib/ignore_it/creator.rb
Labels: feature
